version: "3.8"

services:
  chroncile:
    image: st-microservices/chronicle:${TAG:-latest}
    build:
      context: ./services/chronicle
      dockerfile: Dockerfile
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_CONSOLE=${LOG_CONSOLE}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5100:5100'
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    # Add back when testing true persistence
    #volumes:
      #- ./pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/.pgadmin
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    restart: unless-stopped
    logging:
      driver: none

volumes:
  pgadmin:
  pgdata: