version: "3.8"

services:
  chroncile:
    image: st-microservices/chronicle:${TAG:-latest}
    build:
        context: ./services/chronicle
        dockerfile: Dockerfile
    environment:
        - LOG_LEVEL=${LOG_LEVEL}
        - LOG_CONSOLE=${LOG_CONSOLE}
        - DISCORD_TOKEN=${DISCORD_TOKEN}
    networks:
        - webnet
    ports:
        - 5100:5100
    depends_on:
        - db

  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - webnet

networks:
  webnet:

volumes:
  redis_data:
    driver: local